export { default as Restaurant } from '@/page/restaurant/screens/restaurant'
export { default as RestaurantDetail } from '@/page/restaurant/screens/restaurant-details'
export { default as RestaurantDetailMenu } from '@/page/restaurant/screens/restaurant-details-menu'
export { default as RestaurantDetailMenuList } from '@/page/restaurant/screens/restaurant-details-menu-list'
export { default as RestaurantDetailMenuListDetail } from '@/page/restaurant/screens/restaurant-details-menu-list-detail'
export { default as RestaurantDetailMenuListDetailMenu } from '@/page/restaurant/screens/restaurant-details-menu-list-detail-menu'
