export { default as Bar } from '@/page/bar/screens/bar'
export { default as BarDetail } from '@/page/bar/screens/bar-details'
export { default as BarDetailMenu } from '@/page/bar/screens/bar-detail-menu'
export { default as BarDetailMenuList } from '@/page/bar/screens/bar-detail-menu-list'
export { default as BarDetailMenuListDetail } from '@/page/bar/screens/bar-detail-menu-list-detail'